name: CI-CD Cypress Tests

on:
  push:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./cypress/screenshots
          publish_branch: gh-pages   # branche cible du déploiement
          force_orphan: true         # <--- doit être ici à l’intérieur de "with"